version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: eshop
    ports:
      - '5432:5432'
    container_name: delivery_service_postgres